---
title: "BIOS 611 Project 3"
author: "Xinran Chu"
date: "11/23/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
```

## Read the dataset that was wrangled using Python
```{r }
dat = read_tsv("/Users/September/Documents/GitHub/bios611-projects-fall-2019-September-C/project_3/data/new_dataset.tsv")
```  

```{r }
dat = dat[,-1]
head(dat)
```  

## Explore how the length of stay relates to client demographics  
```{r }
# Extract number of days from the character type variable `Days Stayed` and cast it into int
library(stringr)
numextract <- function(string){ 
  str_extract(string, "\\-*\\d+\\.*\\d*")
} 

days_stayed = numextract(dat$`Days Stayed`)
days_stayed = as.numeric(days_stayed)
dat$`Days Stayed` = days_stayed
```   

### Subset data based on client' demographics for comparison 
```{r }
# Based on client's gender
female = subset(dat, dat$`Client Gender` == "Female")
male = subset(dat, dat$`Client Gender` == "Male")
female = female[-which(is.na(female$`Days Stayed` == "TRUE")), ]
male = male[-which(is.na(male$`Days Stayed` == "TRUE")), ]


# Based on client's age at entry
over_50 = subset(dat, dat$`Client Age at Entry` >= 50)
below_50 = subset(dat, dat$`Client Age at Entry` < 50)

# Based on EE Provider
ses = subset(dat, dat$`EE Provider ID_x` == "Urban Ministries of Durham - Durham County - Singles Emergency Shelter - Private(5838)")

Entry = subset(dat, dat$`EE Provider ID_x` == "XXXClosed2015 Urban Ministries of Durham- Durham County- Journey Entry- ESG(1970)")

Outreach = subset(dat, dat$`EE Provider ID_x` == "XXXClosed2015 Urban Ministries of Durham- Durham County- Journey Outreach- ESG(4515)")

Veterans = subset(dat, dat$`EE Provider ID_x` == "XXXClosed2015 Urban Ministries of Durham- Durham County- Journey Veterans- ESG(5069)")

Forward = subset(dat, dat$`EE Provider ID_x` == "XXXClosed2015 Urban Ministries of Durham- Durham County- Journey Forward- ESG(5694)")

Recovery = subset(dat, dat$`EE Provider ID_x` == "XXXClosed2015 Urban Ministries of Durham- Durham County- Journey Recovery- ESG(1932)")

Tech = subset(dat, dat$`EE Provider ID_x` == "XXXClosed2015 Urban Ministries of Durham- Durham County- Journey Tech- ESG(4516)")

# Based on client's primary race
white = subset(dat, dat$`Client Primary Race` == "White (HUD)")
black = subset(dat, dat$`Client Primary Race` == "Black or African American (HUD)")

# Based on client's ethnicity
non_his_lat = subset(dat, dat$`Client Ethnicity` == "Non-Hispanic/Non-Latino (HUD)")

his_lat = subset(dat, dat$`Client Ethnicity` == "Hispanic/Latino (HUD)")

no_data = subset(dat, dat$`Client Ethnicity` == "Data not collected (HUD)")

refused = subset(dat, dat$`Client Ethnicity` == "Client refused (HUD)")

unknown = subset(dat, dat$`Client Ethnicity` == "Client doesn't know (HUD)")

# Based on veteran status
y_vet =  subset(dat, dat$`Client Veteran Status` == "Yes (HUD)")
n_vet =  subset(dat, dat$`Client Veteran Status` == "No (HUD)")
na_vet = subset(dat, dat$`Client Veteran Status` == "Data not collected (HUD)")

# Based on monthy income at entry (< $3000 or > $3000)
over_3000 = subset(dat, dat$`Monthly Amount (Entry)` >= 3000)
below_3000 = subset(dat, dat$`Monthly Amount (Entry)` < 3000)

# Based on whether client had noncash materials at time of entry
no_dis = subset(dat, dat$`Number of Noncash at Entry` == 0)
yes_dis = subset(dat, dat$`Number of Noncash at Entry` > 0)
```   

### Destinations and reasons for leaving summary 
```{r }
unique(dat$Destination)
unique(dat$`Reason for Leaving`)
```   

```{r }
summary(female$`Days Stayed`)
summary(male$`Days Stayed`)

hist(female$`Days Stayed`)
hist(male$`Days Stayed`)

```  


