---
title: "BIOS 661 Project 1 Draft"
author: "Xinran Chu"
date: "9/22/2019"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
library(tidyverse)
library(knitr)
library(ggplot2)
library(hexbin)
```

```{r echo=T,  message=FALSE}
dat = read_tsv("https://raw.githubusercontent.com/biodatascience/datasci611/gh-pages/data/project1_2019/UMD_Services_Provided_20190719.tsv")

dat = dat[ ,-c(2,3,4,5,8,9,10,11,12,13,14,15,16,17,18)]

dat$Date =  as.Date(dat$Date,'%m/%d/%Y')

dat.food = dat[ ,-2]

dat.food.before.2000 = dat.food %>%
  filter(substr(dat.food$Date, 1, 4) < 2000 & dat.food$`Food Pounds` > 0) 


length(which(!is.na(dat.food.before.2000$`Food Pounds`))) 
# which(!is.na(dat.food.before.2000$`Food Pounds`))

dat.food.2000to2009 = dat.food %>%
  filter(substr(dat.food$Date, 1, 4) < 2010 & substr(dat.food$Date, 1, 4) >= 2000 &   dat.food$`Food Pounds` > 0)
#View(dat.food.2000to2009)

length(which(!is.na(dat.food.2000to2009$`Food Pounds`))) 
#which(!is.na(dat.food.2000to2009$`Food Pounds`))

dat.food.after2009 = dat.food %>%
  filter(substr(dat.food$Date, 1, 4) >= 2010 &   dat.food$`Food Pounds` > 0) 
#View(dat.food.after2009)

length(which(!is.na(dat.food.after2009$`Food Pounds`))) 
#which(!is.na(dat.food.after2009$`Food Pounds`))
```   

```{r }
summary(dat.food.before.2000$`Food Pounds`)
summary(dat.food.2000to2009$`Food Pounds`)
summary(dat.food.after2009$`Food Pounds`)

# total lbs of food provided inn each period
sum(dat.food.before.2000$`Food Pounds`) # 1186 lbs of food provided before 2000
sum(dat.food.2000to2009$`Food Pounds`) # 160116 lbs of food provided between 2000 and 2009
sum(dat.food.after2009$`Food Pounds`) # 1606101 lbs of food provided on and after 2010

# Observe a large increase in the amount of food provided over the years. 
```  

## Plot the trend for each period  

```{r }
ggplot(dat.food.before.2000,aes(x=dat.food.before.2000$Date, y=dat.food.before.2000$`Food Pounds`)) +
  geom_point()+ 
  geom_smooth()

ggplot(dat.food.2000to2009,aes(x=dat.food.2000to2009$Date, y=dat.food.2000to2009$`Food Pounds`)) +
  geom_point() + 
  geom_smooth()

ggplot(dat.food.after2009,aes(x=dat.food.after2009$Date, y=dat.food.after2009$`Food Pounds`)) +
  geom_point() + 
  geom_smooth()
```   

## Number of People for Which Food Was Provided

```{r }
dat.people = dat[ ,-3]

dat.people.before.2000 = dat.people %>%
  filter(substr(dat.people$Date, 1, 4) < 2000 & dat.people$`Food Provided for` > 0) 

dat.people.2000to2009 = dat.people %>%
  filter(substr(dat.people$Date, 1, 4) < 2010 & substr(dat.people$Date, 1, 4) >= 2000  &   dat.people$`Food Provided for` > 0)

dat.people.after2009 = dat.people %>%
  filter(substr(dat.people$Date, 1, 4) >= 2010 & dat.people$`Food Provided for` > 0) 
```  

```{r }
summary(dat.people.before.2000)
summary(dat.people.2000to2009)
summary(dat.people.after2009)
```   

```{r }
ggplot(dat.people.before.2000,aes(x=dat.people.before.2000$Date, y=dat.people.before.2000$`Food Provided for`)) +
  geom_point()+ 
  geom_smooth()

ggplot(dat.people.2000to2009,aes(x=dat.people.2000to2009$Date, y=dat.people.2000to2009$`Food Provided for`)) +
  geom_point() + 
  geom_smooth()

ggplot(dat.people.after2009,aes(x=dat.people.after2009$Date, y=dat.people.after2009$`Food Provided for`)) +
  geom_point() + 
  geom_smooth()
```   

